# Generated by Django 2.2.9 on 2022-05-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220417_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('group', models.CharField(choices=[('Лев Толстой – зеркало русской революции.', 1), ('Свидетели Иеговы', 2), ('группа3', 3)], max_length=100)),
            ],
        ),
    ]
